export const SET_EMAIL = "SET_EMAIL_REGISTER";
export const SET_PASSWORD = "SET_PASSWORD_REGISTER";
export const SET_RES_REGISTER = "SET_RES_REGISTER";
export const RESET_STATE_REGISTER = "RESET_STATE_REGISTER";
