export const SET_PASSWORD = "SET_PASSWORD_RESET_PASSWORD";
export const SET_EMAIL = "SET_EMAIL_RESET_PASSWORD";
export const SET_RES_UPDATE_PASSWORD = "SET_RES_UPDATE_PASSWORD";
export const CLEAN_RESET_PASSWORD = "CLEAN_RESET_PASSWORD";
